name: deploy to test instance
on:
  push:
    branches: [ master ]
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.CICD2 }}
        username: ${{ secrets.CICD2_USERNAME }}
        key: ${{ secrets.CICD2_SECRET }}
        port: ${{ secrets.PORT }}
        script: |
          git config --global --add safe.directory /apps/github-workflows/mhealth-apps/c4c_api/      
          cd /apps/github-workflows/mhealth-apps/c4c_api/
          git pull origin main
          git status
          cp /apps/configs/c4c_api/.env /apps/github-workflows/mhealth-apps/c4c_api/
          cp /apps/configs/c4c_api/docker-compose.yml /apps/github-workflows/mhealth-apps/c4c_api/
          cp /apps/configs/c4c_api/nginx.dockerfile /apps/github-workflows/mhealth-apps/c4c_api/
          cp /apps/configs/c4c_api/php.dockerfile /apps/github-workflows/mhealth-apps/c4c_api/
          cp -r /apps/configs/c4c_api/nginx /apps/github-workflows/mhealth-apps/c4c_api/
          docker-compose stop php
          docker-compose rm -f php
          docker-compose up -d php
           # execute normal laravel commands
          docker-compose exec -T php composer install --ignore-platform-reqs --no-dev
          docker-compose exec -T php php artisan config:cache
          docker-compose exec -T php php artisan view:cache
          docker-compose exec -T php chmod -R 777 storage/
          
