name: deploy to test instance
on:
  push:
    branches: [ master ]
jobs:

  build:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote connection
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.CICD_SECRET }}
        port: ${{ secrets.PORT }}
        script: |
          git config --global --add safe.directory /apps/github-workflows/mhealth-apps/c4c_api/      
          cd /apps/github-workflows/mhealth-apps/c4c_api/
          git pull origin main
          git status
          cp /apps/configs/c4c_api/.env /apps/github-workflows/mhealth-apps/c4c_api/
          cp /apps/configs/c4c_api/docker-compose.yml /apps/github-workflows/mhealth-apps/c4c_api/
          cp /apps/configs/c4c_api/nginx.dockerfile /apps/github-workflows/mhealth-apps/c4c_api/
          cp /apps/configs/c4c_api/php.dockerfile /apps/github-workflows/mhealth-apps/c4c_api/
          cp -r /apps/configs/c4c_api/nginx /apps/github-workflows/mhealth-apps/c4c_api/
          docker-compose down
          docker-compose rm -f
          sudo docker-compose --env-file .env up -d --build site  
          
